openapi: "3.0.0"
info:
  title: TODO API Document
  version: "0.0.1"
  description: TODO API のドキュメントです
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
  /tasks/1:
    get:
      responses:
        '200':
          description: OK